baseurl = "https://abhis.ws" # Hostname (and path) to the root.
title = "Abhishek Dey Das" # Site title.
theme = "hugo-simple-personal-site" # Set the theme.
# languagecode = "en" # The site’s language code.

paginate = 10 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

disableKinds = ["RSS"]

[params] # theme parameters
    author = "Abhishek Dey Das" # Author's name.
    info = "Software Development Engineer at Amazon" # Author's job title or info.
    description = "Abhishek Dey Das's personal website" # Site description.
    introduction = "Hello and welcome to my homepage. I am a software engineer, foodie and an amateur photographer."
    aboutpage = "/about/"
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/abhishek.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "All copyrights reserved. All opinions are personal and does not reflect that of my employer or organizations I am associated with." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = ["css/custom.css"]

    # RTL support
    rtl = false

    email = "abhishek@abhis.ws"

    facebook = "adeydas"

    twitter = "adeydas"

    linkedin = "adeydas"

    github = "adeydas"

# Social links
[[params.social]]
    name = "LinkedIn"
    weight = 1
    url = "https://www.linkedin.com/in/adeydas/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/adeydas"
[[params.social]]
    name = "Email"
    weight = 3
    url = "/email-me/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
	name = "Projects"
	weight = 2
	url = "/projects/"
[[menu.main]]
	name = "Photos"
	weight = 4
	url = "https://www.flickr.com/photos/adeydas"