baseurl = "https://abhis.ws" # Hostname (and path) to the root.
title = "Abhishek Dey Das" # Site title.
theme = "hugo-coder" # Set the theme.
# languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

[params] # theme parameters
    author = "Abhishek Dey Das" # Author's name.
    info = "Software Development Engineer at Amazon" # Author's job title or info.
    description = "Abhishek Dey Das's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/abhishek.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "All copyrights reserved. All opinions are personal and does not reflect that of my employer or organizations I am associated with." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/adeydas/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/adeydas/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/adeydas/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
	name = "Projects"
	weight = 2
	url = "/projects/"